kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: gnizharadze
spec:
  servers:
    - hosts:
        - {{ .Release.Name }}-gnizharadze.apps.osh.devops.tbc
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway