apiVersion: v1
kind: Service
metadata:
  name: vue-todo-service
  namespace: gnizharadze
  labels:
    app: vue-todo-service
spec:
  selector:
    app: vue-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80